---
title: "Reproducible Research Week 1 Notes"
author: "Millie"
date: "Tuesday, January 05, 2016"
output: html_document
---

Load data
```{r}
library(kernlab)
data(spam)
str(spam[, 1:5])
```

Testing and training
```{r}
set.seed(3435)
trainIndicator=rbinom(4601, size=1, prob=0.5)
table(trainIndicator)
trainSpam=spam[trainIndicator==1,]
testSpam=spam[trainIndicator==0,]
```

Exploratory data analysis- training data
```{r}
names(trainSpam)
head(trainSpam)
table(trainSpam$type)
plot(trainSpam$capitalAve~trainSpam$type)#skew, transform and replot
plot(log10(trainSpam$capitalAve+1)~trainSpam$type)#add 1 to prevent log issues for values=0
plot(log10(trainSpam[,1:4]+1))#for pairwise relationships
hCluster=hclust(dist(t(trainSpam[, 1:57])))#across data comparisons, sensitive to skewness
plot(hCluster)
hClusterUpdated=hclust(dist(t(log10(trainSpam[, 1:55]+1))))#transform and replot
plot(hClusterUpdated)
```

Statistical prediction/modeling
```{r}
trainSpam$numType=as.numeric(trainSpam$type)-1
costFunction=function(x,y) sum(x!=(y>0.5))
cvError=rep(NA, 55)
library(boot)
for(i in 1:55){
  lmFormula=reformulate(names(trainSpam)[i], response="numType")
  glmFit=glm(lmFormula, family="binomial", data=trainSpam)
  cvError[i]=cv.glm(trainSpam, glmFit, costFunction, 2)$delta[2]
}
##which predictor has the minimum cross-validationi error?
names(trainSpam)[which.min(cvError)]
```

Get a measure of uncerntainty
```{r}
##Use best model from group
predictionModel=glm(numType~charDollar, family="binomial", data=trainSpam)

##Get predictions on the test set
predictionTest=predict(predictionModel, testSpam)
predictedSpam=rep("nonspam", dim(testSpam)[1])

##Classify as 'spam' for those with prob > 0.5
predictedSpam[predictionModel$fitted > 0.5]="spam"

##Classification table
table(predictedSpam, testSpam$type)

##Calculate error rate
(61+458)/(1346+458+61+449)
``` 



